export enum ActionType {
    FETCH_ALL_COUPONS,
    FILTER_COUPONS_BY_CATEGORY,
    FILTER_COUPONS_BY_PRICE_RANGE,
    FILTER_COUPONS_BY_TITLE,
    FILTER_COUPONS_BY_DATE_RANGE,
    FILTER_COUPONS_BY_COMPANY,


}
